language: node_js
node_js:
- '6'
branches:
  except:
  - releases
matrix:
  include:
    - env: JOB=unit
    - env: JOB=e2e-guru
  fast_finish: true
  allow_failures:
    - env: JOB=e2e-guru
env:
  global:
  - SAUCE_USERNAME: redoc
  - secure: OgYIXlyF3tvHVrMjqIMR7UPhNvMzNZRkKE++LsQPUT4aoUmHoeukjgE9tKCZac3Z+PcAlgHQ6dPUqjqij2d/emYBIrCx4ABvTOnxQYHbk+8GriwPvQjV33MCfKvRQAf3XPNcga02aOO/EEGejrtY/i5sz86XPZFXap4scxbvnF0rzOwGU9/A40JLsvKjtfdRxJ3aC2QBnUHP9JkfBOzbs3jjwEWYN7HdUBqtYU+wiUwvHhpEPQ8BVNF5ETp5OxxkTdqJlMRf3azC4U/Rl8dhUXZP2l1ZBdpgahDvSkx1zXPwKRg1jos88jahqH/v8DLHtXNuYQy4S48nKWZfaRtQegG/XsYAftYPtYage7L9D0nFQW9YZI0vwUBEzh2YTf+QNpVwUSyZhVuS1oS+scTb8RU8BVVZd6hRpJiaI2YiPM6ZFN7a69deV0cASov3yI7GSfeq4MmB4hu72Le+GhemQMLRxNgtr32c18XW1XoHEnpV7s0eKXnZrevnM06tW/nX9TQXGloaMUeQzoZY0AuF00zmrHDaNgwT63ULjY0W591Ey1Ztfq4ixdCoi6IPAtl49vTnNMMMqatI7Si/haI6hGyTy+H0xK1GlUpBCe5CGusXDSKUqrlKS5Izreepfj1G+12391ixiapkwV3SbYdQEhcDt7HWupyI4Zfkvg8EwwE=
  - secure: H2GClDJ7TEQaWgnk8d2fIVDpLwG3rTmN8TalUzrCqXGoG6ylCVmlwzKLgfPPWrVgSA7QTdfNV0ab7c2KyPoZBinHmeGMSuKNLVbhOXRc2VFxTBntBTuyJhfCgQEpUKvJesJUuv5RuBn//wC7VZcVVNc06TZDEe8+aDVYQuCRMXZJ4X3e6nSZ64QX2veyVcr+TjnRsZPkeBVcK9hngvuaxLb/hbJ85CvjiseZRt47PGIcrEpMn9n2GMw1m0fNnPoN+MBTSCnIklTmdjPG7t4GUSLmD6H0lNLdXuehYqmQAHgYrLec1aiFlV57QaDoDZrq2hSf4vDmCB/FVydGhD5JunI67pujoV2OnD1V80eUZhYNWOYsJ2Nfp4NxgXsPUcE6zWLYsLfktMPZADhOXInQRACt1cnx8zMYKLnch1RY/ZqjSg0nPtRjLzQ0lNsw5leixvBdBnMjxYHVyAWVwg8WiJMaLO9vog2Qnxg1NTacHO2CsOmm2rw6stpg7ndp/+nOleRlfUKggjt0Tn3FjwCIXeGup2P2EBa+WW2YMAaoMFofYviR5vRlKBgdKo9fsAruaO1r6nm2EdAjOlniyw92bEfU/qOey1nVp/oK2S82uT5In8KB7vl6rF3ak7WAsT9Q5vZUhsrG+eE4PVyIyWNBhs4A7pSwZGHDR/MYtp0E2ug=
  - secure: apiavCfCQngL9Een1m7MIXMf3bqO3rY4YY59TMBl/yFKi80CEsHPHhgVUkl6hC+aM5PeBt/vgjh37rHMX31j/pcSZ4Z8SO/4Bwr36iHfhSxSEuAQog8P07qWqH7wYYWGIVmF682stgl0fYF+GN92sx/6edFVzsWVECf2G7imtICKSTbhKGm3Dhn2JwGnhD7eyfgZ33omgiaswumdu0xABoXDfqSZR+16fC4Ap5rhv3fXO9ndvRNy1STn376nT+my6e86UrQL4aS/S+HNHgIe1BUs+5cOp6Jgw6t0ie7phY0EAiECsRxy9K4e3Dctv9m6+Wma4+vy65MS0zGyrqey6oyV4l827sCOjrD1qcqc9bX6FlMSouVoNfE4ZjINNAbgigTaiLSoDSPcf5I5smkkM2ezzFOMSZwZxNdaNL2LKb97vc8m/ZUkv0sKZyT7oqVL7aJweEivsSHj5l2KR8Z7XrVB1y2eI6GvyTSa/d+CL4dSRzjh8+IRN047YBrdTKD5IkdT0upfoBu14WPUfFmLKxX+iMCslXRWb6kwojhrWNYmZvL65KRAzJ6+eIPDG/W5QUOpYyYT77bLlBQjVo6NmVvl9v3HMECq9CHH0ivKFBGPiKMOx7cJkTax3FuyznOW2WCXB9kTb5Zk9toaiNlSp9L6ll/h2Eyxa6n6sWUgmmM=
addons:
  sauce_connect: true
  chrome: stable
cache: yarn
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
before_deploy:
- if [[ ! -z "$TRAVIS_TAG" ]]; then npm run build:all; fi
deploy:
  - provider: npm
    skip_cleanup: true
    email: gotsijroman@gmail.com
    api_key:
      secure: TJlRyyXdH/lSRKQkV1RQ0cAWGY5Go0IxWmCV+q4LQPtaisqvZJDu9FG0vFSDYAncDGkUkhgy3CNMl+6T5U21LDNz3pt7Uy8LIbJpVGW3aIlWDO14oVd6pjDwGT/72P3+sL/5Bsr/rhVqe7N3o49xdfE8kM3PBeJwFfwynYvWuegTy7LnbQTAWNv7MJXnM/fwNS0Yo5hfm7VhIBgac1o9mEiklX0DBk189rva45Q95nG2t6Me6dS+TYXDXN1cDuPIAqBxINNWEbIFXCJv9Wq3uEicS3zyoso0tEwtdSJh2zkhc7wEZRGvMpzMmkY5C5vS7QgkJBpvlc/aFqJvkp1wJMEwU4Ti6T6/PR05yJCKmam/FE49iMuy3CnaWm/NfExxEHRyIvfR8ZQxqXrzEkSZSG9tHNVynaF53dGLSU9swk5bR6Ru9ROTwijxwZjzr2qsdUCSXk+zIbE6+s2zDwJm3FIpAMhbRjCo5+sDxO6q8+Lhi4ugffEB7UsN6Vo9m/HcUOcmCiqwx4AriNBrvFocs5koW0pWpTLql+MMCJMlh5lE86oc4/PdUysZgh7afPUalBWTdE0E3TGRm89f27QgDxnPMMH1OFuuSPXrf405gDy8oBh+MnXBEAq/pIRf+DnK6ja/T7aPdOVpb2pfe3y4Zjq8ThnXvjSI68hptQsifGs=
    on:
      tags: true
      condition: $JOB != e2e-guru
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      tags: true
      condition: $JOB != e2e-guru
